version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Mock vagrant
          command: |
            sudo bash .circleci/mock_vagrant.sh
      - run:
          name: Download python environment manager
          command: |
            sudo bash .circleci/download_python_environment_manager.sh
      - run:
          name: Install deps
          command: |
            cd /vagrant; sudo bash .tmp/python-environment-manager-master/makefile_resources/scripts_python/conda/install_apt_dependencies.sh inflation vagrant linux
      - run:
          name: Install python
          command: |
            cd /vagrant; sudo bash .tmp/python-environment-manager-master/makefile_resources/scripts_python/conda/install_python.sh inflation vagrant linux
      - run:
          name: Install app
          command: |
            cd /vagrant; sudo bash .tmp/python-environment-manager-master/makefile_resources/scripts_python/conda/install_app.sh inflation vagrant linux
      - run:
          name: Run tests
          command: |
            cd /vagrant; sudo bash .tmp/python-environment-manager-master/makefile_resources/scripts_python/conda/run_tests.sh inflation vagrant linux
