name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Full build
      run: |
        sudo bash .repo/mock_vagrant.sh
        sudo bash .repo/download_python_environment_manager.sh
        cd /vagrant; sudo bash .tmp/bash-environment-manager-master/makefile_resources/scripts_python/install_python.sh inflation vagrant vagrant
        cd /vagrant; sudo bash .tmp/bash-environment-manager-master/makefile_resources/scripts_python/install_app.sh inflation vagrant vagrant
        cd /vagrant; sudo bash .tmp/bash-environment-manager-master/makefile_resources/scripts_python/run_tests.sh inflation vagrant vagrant
