name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Full build
      run: |
      sudo bash .gitlabci/mock_vagrant.sh
      sudo bash .gitlabci/download_python_environment_manager.sh
